# Generated by Django 3.2.25 on 2025-02-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
