# Generated by Django 3.2.25 on 2025-02-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_category_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='batch_no',
            field=models.CharField(max_length=50),
        ),
    ]
