# Generated by Django 3.2.25 on 2025-02-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_sale_saleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('doctor_name', models.CharField(max_length=200)),
                ('prescription_date', models.DateField(auto_now_add=True)),
                ('prescription_file', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
