# Generated by Django 3.2.25 on 2025-02-10 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.sale'),
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
