# Generated by Django 3.2.25 on 2025-02-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_auto_20250210_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='requires_prescription',
            field=models.BooleanField(default=False),
        ),
    ]
